#!/usr/bin/env python

import re

from lib.core.enums import PRIORITY

__priority__ = PRIORITY.LOWEST

def dependencies():
    pass

def tamper(payload, **kwargs):

    retVal = payload

    if payload:
        retVal = re.sub(r"(?i)\bSELECT\b", "select/**/", re.sub(r"(?i)\bORD\b", "ORD/**/",re.sub(r"(?i)\bUNION\b", "", payload)))

    return retVal
